version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install doxygen
            sudo apt-get remove cmake
            wget https://cmake.org/files/v3.10/cmake-3.10.2-Linux-x86_64.sh
            sudo bash cmake-3.10.2-Linux-x86_64.sh --skip-license --exclude-subdir --prefix=/usr/local
      - run:
          name: init
          command: |
            git submodule sync
            git submodule update --init
            git submodule sync
            git submodule update --init
      - run:
          name: Print the Current Time
          command: date
